name: finansaurus_repository
description: The repository that handles finansaurus related request.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  finansaurus_api:
    path: ../finansaurus_api

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2