name: authenticated_http_client
description: The Flutter implementation of an authenticated http client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cache:
    path: ../cache

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.16.4
